version: '3.8'
services: 
  minio:
    image: minio/minio
    container_name: minio_local_app
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Admin1234
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  
  spark-master:
    image: bitnami/spark:latest
    container_name: spark_local_app
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark_local_app
    volumes:
      - ./spark:/opt/spark/conf
      - ./notebooks:/opt/apps

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker_local_app
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark_local_app:7077
    volumes:
      - ./spark:/opt/spark/conf
      - ./notebooks:/opt/apps
  hive-metastore-db:
    image: postgres
    container_name: hive-metastore-db
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    ports:
      - "5432:5432"
    volumes:
      - metastore_data:/var/lib/postgresql/data

  hive-metastore:
    image: bitsondatadev/hive-metastore
    container_name: hive-metastore
    ports:
      - "9083:9083"
    environment:
      - METASTORE_DB_HOSTNAME=hive-metastore-db
      - METASTORE_TYPE=postgres
      - METASTORE_DB_PORT=5432
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    depends_on:
      - hive-metastore-db
  
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    ports:
      - "10000:10000" 
      - "10002:10002"
    environment:
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - SERVICE_NAME=hiveserver2
    volumes:
      - ./core-site.xml:/opt/hadoop-2.7.4/etc/hadoop/core-site.xml
    depends_on:
      - hive-metastore
      - hdfs_namenode
  hdfs_namenode:
    image: bde2020/hadoop-namenode
    container_name: hdfs_namenode
    ports:
      - "50070:50070"
      - "8020:8020"
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - namenode_data:/hadoop/dfs/name
  hdfs_datanode:
    image: bde2020/hadoop-datanode
    container_name: hdfs_datanode
    depends_on:
      - hdfs_namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - datanode_data:/hadoop/dfs/data

volumes:
  minio_data:
  metastore_data:
  namenode_data:
  datanode_data:
    

  