  services:
    minio:
      image: minio/minio
      container_name: minio
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: Admin1234
      volumes:
        - minio_data:/data
      command: server /data --console-address ":9001"

    spark-master:
      image: bitnami/spark:latest
      container_name: spark-master
      environment:
        - SPARK_MODE=master
      ports:
        - "8080:8080"
      networks:
        - spark-net

    spark-worker1:
      image: bitnami/spark:latest
      container_name: spark-worker1
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      ports:
        - "8081:8081"
      networks:
        - spark-net
      depends_on:
        - spark-master

    spark-worker2:
      image: bitnami/spark:latest
      container_name: spark-worker2
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      ports:
        - "8082:8081"
      networks:
        - spark-net
      depends_on:
        - spark-master

    hive-metastore:
      image: apache/hive:4.0.1
      container_name: hive-metastore
      environment:
        HIVE_METASTORE_URI: thrift://hive-metastore:9083
      ports:
        - "9083:9083"
      depends_on:
        - spark-master
      networks:
        - spark-net

    kyuubi:
      image: apache/kyuubi:master-snapshot
      container_name: kyuubi
      ports:
        - "10009:10009"   # JDBC connection
        - "10099:10099"   # Web UI / Monitoring
      environment:
        KYUUBI_ENGINE_SHARE_LEVEL: USER
      depends_on:
        - spark-master
        - hive-metastore
      networks:
        - spark-net
  
    jupyter:
      image: jupyter/all-spark-notebook
      container_name: jupyter
      ports:
        - "8888:8888"
      volumes:
        - jupyter_data:/home/jovyan
      networks:
        - spark-net

    trino:
      image: trinodb/trino
      container_name: trino
      ports:
        - "8088:8080"
      networks:
        - spark-net

  volumes:
    minio_data:
    jupyter_data:

  networks:
    spark-net:
